InternationalRegistration/Controllers/DocumentsController.cs
using System.Web;
using System.Web.Mvc;
using System.Linq;
using System.Collections.Generic;
using System;
using System.Web.Configuration;
using ISR.Services;
using ISR.Commons;
using ISR.DAL.Amozesh_Initial;
using ISR.Commons.enums;
using ISR.web.Models;

namespace ISR.web.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly IStudentDocService studentDocSVC;
        private readonly IEducationDegreeService educationDegreeSVC;
        private readonly IRequestService requestSVC;
        private readonly ICountryService countrySVC;
        private readonly ICitizenShipService citizenShipSVC;
        private readonly IFieldForForeignService fieldsSVC;
        private readonly IAccountService accountSVC;

        //base model for docs
        string basePath = "st_documents";
        string term = WebConfigurationManager.AppSettings["Term"];
        byte docStatus = (byte)DocStatus.InProgress;
        byte Karshenas_UpdateDocStatus = (byte)DocStatus.Accepted;


        bool active = true;

        public DocumentsController(IStudentDocService studentDocsService
            , IEducationDegreeService educationDegreeService
            , IRequestService requestService
            , ICitizenShipService citizenShipService
            , IFieldForForeignService fieldService
            , ICountryService countryService
            , IAccountService accountService
            , IStudentDocService studentDocService)
        {
            studentDocSVC = studentDocsService;
            educationDegreeSVC = educationDegreeService;
            requestSVC = requestService;
            citizenShipSVC = citizenShipService;
            fieldsSVC = fieldService;
            countrySVC = countryService;
            accountSVC = accountService;
            studentDocSVC = studentDocService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UploadDocuments()
        {

            Session["lang"] = WebConfigurationManager.AppSettings["DefaultLang"];
            if (Session["UserInfo"] == null || Session["RequestId"] == null)
                return RedirectToRoute("Default", new { lang = Session["lang"], controller = "Account", action = "Index" });

            var req = requestSVC.FindById(decimal.Parse(Session["RequestId"].ToString()));
            ViewBag.St_Request = req;
            ViewBag.St_LastLevel = req.Student?.EducationDegrees?.OrderByDescending(ord => ord.Level).FirstOrDefault();


            //var accountId = 5;//(Session["UserInfo"] as Models.UserViewModel).Id;
            TempData["studentID"] = req.StudentId; //accountSVC.FindById(accountId).StudentId;

            //var countries = new SelectList(countrySVC.FetchAll().OrderBy(o => o.Name), "Id", "DisplayName").ToList();
            //countries.Insert(0, new SelectListItem { Text = Resources.Dropdown_Choose, Value = "0" });
            //ViewBag.CountryList = countries;

            //var fields = new SelectList(fieldsSVC.FetchAll().OrderBy(o => o.Field_Name), "Id", "Field_Name").ToList();
            //fields.Insert(0, new SelectListItem { Text = Resources.Dropdown_Choose, Value = "0" });
            //ViewBag.AllFields = fields;

            var docs = studentDocSVC.FetchMany(doc => doc.SudentId == req.StudentId).ToList();

            var docPersonalPicture = docs.FirstOrDefault(doc => doc.FileName.Contains(DocumentsMangement.PersonalPicture));
            ViewBag.vbPersonalPicture = docPersonalPicture == null ? "#" : docPersonalPicture.Path + "/" + docPersonalPicture.FileName + "?ts=" + Helpers.TimeStamp();


            var docPassport = docs.FirstOrDefault(doc => doc.FileName.Contains(DocumentsMangement.Passport));
            ViewBag.vbPassport = docPassport == null ? "#" : docPassport.Path + "/" + docPassport.FileName + "?ts=" + Helpers.TimeStamp();

            var docDiploma = docs.FirstOrDefault(doc => doc.FileName.Contains(DocumentsMangement.Diploma));
            ViewBag.vbDiploma = docDiploma == null ? "#" : docDiploma.Path + "/" + docDiploma.FileName + "?ts=" + Helpers.TimeStamp();

            var docCollage = docs.FirstOrDefault(doc => doc.FileName.Contains(DocumentsMangement.Collage));
            ViewBag.vbCollage = docCollage == null ? "#" : docCollage.Path + "/" + docCollage.FileName + "?ts=" + Helpers.TimeStamp();

            var docBachelor = docs.FirstOrDefault(doc => doc.FileName.Contains(DocumentsMangement.Bachelor));
            ViewBag.vbBachelor = docBachelor == null ? "#" : docBachelor.Path + "/" + docBachelor.FileName + "?ts=" + Helpers.TimeStamp();

            var docMaster = docs.FirstOrDefault(doc => doc.FileName.Contains(DocumentsMangement.Master));
            ViewBag.vbMaster = docMaster == null ? "#" : docMaster.Path + "/" + docMaster.FileName + "?ts=" + Helpers.TimeStamp();

            var docPhd = docs.FirstOrDefault(doc => doc.FileName.Contains(DocumentsMangement.Phd));
            ViewBag.vbPhd = docPhd == null ? "#" : docPhd.Path + "/" + docPhd.FileName + "?ts=" + Helpers.TimeStamp();


            return View();
        }


        //private bool formDataIsValid()
        private bool formDataIsValid(HttpPostedFileBase personalPicture, HttpPostedFileBase passport, HttpPostedFileBase diploma, HttpPostedFileBase collage, HttpPostedFileBase bachelor, HttpPostedFileBase master, HttpPostedFileBase phd, string lastEducationDegree = "0", string curentLevel = "0")
        {
            bool res = true;
            string errMessages = "";
            var stID = (TempData["studentID"] as decimal?);
            var docs = studentDocSVC.FetchMany(doc => doc.SudentId == stID && doc.Term == this.term);

            if (docs.Count() == 0)
            {
                if (lastEducationDegree == "0")
                {
                    errMessages += Resources.Resources.ValidationMessage_LastEducationDegree;//"آخرین مدرک تحصیلی انتخاب نشده است";
                    errMessages += "#";
                    res = false;
                }

                if (curentLevel == "0")
                {
                    errMessages += Resources.Resources.ValidationMessage_CurrentLevel;//" مقطع جاری انتخاب نشده است";
                    errMessages += "#";
                    res = false;
                }

                if (personalPicture == null)
                {
                    errMessages += Resources.Resources.ValidationMessage_PersonalPictureDocIsRequired; //" بارگذاری مدرک عکس پرسنلی الزامی می باشد";
                    errMessages += "#";
                    res = false;
                }


                if (passport == null)
                {
                    errMessages += Resources.Resources.ValidationMessage_PassportDocIsRequired; //" بارگذاری گذرنامه الزامی می باشد";
                    errMessages += "#";
                    res = false;
                }

                switch (curentLevel)
                {
                    case "1"://Diploma
                    case "2"://collage --> pish daneshgahi
                    case "3"://bachelor --> lisence
                        if (diploma == null)
                        {
                            errMessages += Resources.Resources.ValidationMessage_DiplomaDocIsRequired; //" بارگذاری مدرک دیپلم برای مقطع انتخابی الزامی می باشد";
                            errMessages += "#";
                            res = false;
                        }
                        break;

                    case "4"://master
                        if (bachelor == null)
                        {
                            errMessages += Resources.Resources.ValidationMessage_BachelorDocIsRequired; //" بارگذاری مدرک کارشناسی برای مقطع انتخابی الزامی می باشد";
                            errMessages += "#";
                            res = false;
                        }
                        break;

                    case "5"://phd
                        if (master == null)
                        {
                            errMessages += Resources.Resources.ValidationMessage_MasterDocIsRequired; ; //" بارگذاری مدرک کارشناسی ارشد برای مقطع انتخابی الزامی می باشد";
                            res = false;
                        }
                        break;
                }

            }
            else
            {
                if (docs.Count() < 3)
                {
                    if (lastEducationDegree == "0")
                    {
                        errMessages += Resources.Resources.ValidationMessage_LastEducationDegree;//"آخرین مدرک تحصیلی انتخاب نشده است";
                        errMessages += "#";
                        res = false;
                    }

                    if (curentLevel == "0")
                    {
                        errMessages += Resources.Resources.ValidationMessage_CurrentLevel;//" مقطع جاری انتخاب نشده است";
                        errMessages += "#";
                        res = false;
                    }

                    if ((!docs.Any(doc => doc.FileName.Split('.')[0].ToLower() == DocumentsMangement.PersonalPicture.ToLower()) && personalPicture == null))
                    {
                        errMessages += Resources.Resources.ValidationMessage_PersonalPictureDocIsRequired; //" بارگذاری مدرک عکس پرسنلی الزامی می باشد";
                        errMessages += "#";
                        res = false;
                    }


                    if ((!docs.Any(doc => doc.FileName.Split('.')[0].ToLower() == DocumentsMangement.Passport.ToLower()) && passport == null))
                    {
                        errMessages += Resources.Resources.ValidationMessage_PassportDocIsRequired; //" بارگذاری گذرنامه الزامی می باشد";
                        errMessages += "#";
                        res = false;
                    }

                    //!(Array.IndexOf(new List<String>() { "1", "2", "3", "4", "5" }.ToArray(), lastEducationDegree) > -1)

InternationalRegistration/Views/Documents/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

InternationalRegistration/Views/Documents/UploadDocuments.cshtml
@using ISR.Resources
@using ISR.DAL.Amozesh_Initial
<style>
    .alert-box {
        width: 100%;
        margin-top: 15px;
    }

    .form-width {
        width: 100%;
    }

    .doc-wapper {
        background: #ddd;
        margin-top: 15px;
        margin-bottom: 15px;
    }

    table {
        background: #ddd;
    }

    button[id^='ddl_Candidate_Fields'] {
        min-height: 38px;
    }

    input[type=search] {
        width: 87%;
    }

    .ast-span {
        font-size: 30px;
        color: red;
    }

    .div-display-flex {
        display: flex;
    }

        .div-display-flex > span {
            font-size: 30px;
            font-weight: bolder;
            color: red;
        }
</style>
<div class="alert alert-danger alert-box">
    <p> * @Resources.RequiredField_Astericks</p>
</div>
@using (Html.BeginForm("UploadDocuments", "Documents", FormMethod.Post, new { id = "frmUploadDocuments", enctype = "multipart/form-data", @class = "form-width" }))
{

    if (!string.IsNullOrEmpty(TempData["ErrMessages"] as string))
    {
        <div class="alert alert-danger">
            @{
                var errMsgs = (TempData["ErrMessages"] as string).Split('#');
                for (int k = 0; k < errMsgs.Length; k++)
                {
                    <p> * @errMsgs[k]</p>
                }
            }
        </div>
    }
    <div class="doc-wapper">
        <div class="form-row">
            <div class="form-group col-md-5">
                <label for="lastEducationDegree"> @Resources.Last_Education_Degree</label>
                <input type="hidden" name="txt_LastEducationDegree" id="txt_LastEducationDegree" />
                <div class="div-display-flex">
                    <span>*</span>
                    <select class="form-control" id="ddl_LastEducationDegree">
                        @{
                            string selected_0_lastLevel = ""
                                , selected_1_lastLevel = ""
                                , selected_2_lastLevel = ""
                                , selected_3_lastLevel = ""
                                , selected_4_lastLevel = ""
                                , selected_5_lastLevel = "";
                            if (ViewBag.St_LastLevel != null)
                            {
                                switch ((ViewBag.St_LastLevel as EducationDegree).Level.ToString())
                                {
                                    case "0": selected_0_lastLevel = "selected"; break;
                                    case "1": selected_1_lastLevel = "selected"; break;
                                    case "2": selected_2_lastLevel = "selected"; break;
                                    case "3": selected_3_lastLevel = "selected"; break;
                                    case "4": selected_4_lastLevel = "selected"; break;
                                    case "5": selected_5_lastLevel = "selected"; break;                                   
                                }
                            }
                        }
                        <option @selected_0_lastLevel value="0">@Resources.Dropdown_Choose</option>
                        <option @selected_1_lastLevel value="1">@Resources.Diploma</option>
                        <option @selected_2_lastLevel value="2">@Resources.Collage</option>
                        <option @selected_3_lastLevel value="3">@Resources.Bachelor</option>
                        <option @selected_4_lastLevel value="4">@Resources.Master</option>
                        <option @selected_5_lastLevel value="5">@Resources.Phd</option>                        
                    </select>
                </div>

            </div>
            <div class="form-group col-md-2"></div>

            <div class="form-group col-md-5">
                <label for="currentLevel">@Resources.Current_Level</label>
                <input type="hidden" name="txt_CurentLevel" id="txt_CurentLevel" />
                <div class="div-display-flex">
                    <span>*</span>
                    @{
                        string selected_0_currentLevel = ""
                            , selected_1_currentLevel = ""
                            , selected_2_currentLevel = ""
                            , selected_3_currentLevel = ""
                            , selected_4_currentLevel = ""
                            , selected_5_currentLevel = "";
                        if (ViewBag.St_Request != null)
                        {
                            switch ((ViewBag.St_Request as Request).CurrentLevel.ToString())
                            {
                                case "0": selected_0_currentLevel = "selected"; break;
                                case "1": selected_1_currentLevel = "selected"; break;
                                case "2": selected_2_currentLevel = "selected"; break;
                                case "3": selected_3_currentLevel = "selected"; break;
                                case "4": selected_4_currentLevel = "selected"; break;
                                case "5": selected_5_currentLevel = "selected"; break;                               
                            }
                        }
                        <select class="form-control" id="ddl_CurrentLevel">
                            <option @selected_0_currentLevel value="0">@Resources.Dropdown_Choose</option>
                            <option @selected_1_currentLevel value="1">@Resources.Diploma</option>
                            <option @selected_2_currentLevel value="2">@Resources.Collage</option>
                            <option @selected_3_currentLevel value="3">@Resources.Bachelor</option>
                            <option @selected_4_currentLevel value="4">@Resources.Master</option>
                            <option @selected_5_currentLevel value="6">@Resources.Phd</option>
                        </select>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table uploadDocuments">
            <thead>
                <tr>
                    <th scope="col">@Resources.Doc_Name</th>
                    <th scope="col">*</th>
                    <th scope="col">@Resources.Doc_Upload</th>
                    <th scope="col">@Resources.Doc_Preview</th>
                    @*<th scope="col">@Resources.Doc_Status</th>*@
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Resources.PersonalPicture</td>
                    <td><span class="ast-span pass">*</span></td>
                    <td><input id="PersonalPicture" type="file" name="PersonalPicture_f"></td>
                    <td>
                        <img src="@ViewBag.vbPersonalPicture" id="imgPersonalPicture">
                    </td>
                    @*<td>@Resources.Status_Alaki_Text</td>*@
                </tr>
                <tr>
                    <td>@Resources.Passport</td>
                    <td><span class="ast-span pass">*</span></td>
                    <td><input id="Passport" type="file" name="Passport_f"></td>
                    <td>
                        <img src="@ViewBag.vbPassport" id="imgPassport">
                    </td>
                    @*<td>@Resources.Status_Alaki_Text</td>*@
                </tr>

                <tr>
                    <td>@Resources.Diploma</td>
                    <td><span class="ast-span">*</span></td>
                    <td><input id="Diploma" type="file" name="Diploma_f"></td>
                    <td>
                        <img src="@ViewBag.vbDiploma" id="imgDiploma">
                    </td>
                    @*<td>@Resources.Status_Alaki_Text</td>*@
                </tr>

                <tr>
                    <td>@Resources.Collage</td>
                    <td><span class="ast-span">*</span></td>
                    <td><input id="Collage" type="file" name="Collage_f"></td>
                    <td>
                        <img src="@ViewBag.vbCollage" id="imgCollage">
                    </td>
                    @*<td>@Resources.Status_Alaki_Text</td>*@
                </tr>

                <tr>
                    <td>@Resources.Bachelor</td>
                    <td><span class="ast-span">*</span></td>
                    <td><input id="Bachelor" type="file" name="Bachelor_f"></td>
                    <td>
                        <img src="@ViewBag.vbBachelor" id="imgBachelor">
                    </td>
                    @*<td>@Resources.Status_Alaki_Text</td>*@
                </tr>

                <tr>
                    <td>@Resources.Master</td>
                    <td><span class="ast-span">*</span></td>
                    <td><input id="Master" type="file" name="Master_f"></td>
                    <td>
                        <img src="@ViewBag.vbMaster" id="imgMaster">
                    </td>
                    @*<td>@Resources.Status_Alaki_Text</td>*@
                </tr>

                <tr>
                    <td>@Resources.Phd</td>
                    <td><span class="ast-span">*</span></td>
                    <td><input id="Phd" type="file" name="Phd_f"></td>
                    <td>
                        <img src="@ViewBag.vbPhd" id="imgPhd">
                    </td>
                    @*<td>@Resources.Status_Alaki_Text</td>*@
                </tr>

            </tbody>
        </table>
    </div>

    <input type="submit" id="btnSubmitDocs" name="btnSubmitDocs" value="@Resources.Doc_Upload_Btn" class="btn btn-success">
    <br />
    <br />
}